---

- name: Check if superuser credentials exist for amp website
  shell:
    cmd: >
      echo "get ampy/views_password" | debconf-communicate >/dev/null || echo "missing"
  register: check_ampweb_password_set
  changed_when: "'missing' in check_ampweb_password_set.stdout"

- name: Set initial amp website username
  debconf:
    name: ampy
    question: ampy/views_user
    value: "{{ ampweb_username }}"
    vtype: string
  when:
    - "'stdout' in check_ampweb_password_set"
    - "'missing' in check_ampweb_password_set.stdout"

- name: Set initial amp website password
  debconf:
    name: ampy
    question: ampy/views_password
    value: "{{ ampweb_password }}"
    vtype: password
  when:
    - "'stdout' in check_ampweb_password_set"
    - "'missing' in check_ampweb_password_set.stdout"

- name: Install AMP server packages
  apt:
    pkg:
      - amp-web
    state: present
  notify: restart apache

# Apache configuration for ampweb
- name: Configure /etc/ampweb/ampweb.conf
  template:
    src: "templates/ampweb/ampweb.conf"
    dest: "/etc/ampweb/ampweb.conf"
  notify: reload apache

# ampweb graphing and data endpoint configuration
- name: Configure /etc/ampweb/production.ini
  template:
    src: "templates/ampweb/production.ini"
    dest: "/etc/ampweb/production.ini"
  notify: reload apache
