---

- name: Enable apache modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - ssl
    - rewrite
    - headers
  notify: restart apache

- name: Configure apache vhosts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/apache2/sites-available/{{ item | basename }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob:
    - "templates/apache/sites-available/*"
  notify: reload apache

- name: Activate apache vhosts
  ansible.builtin.file:
    src: "/etc/apache2/sites-available/{{ item | basename }}"
    dest: "/etc/apache2/sites-enabled/{{ item | basename }}"
    owner: root
    group: root
    state: link
  with_fileglob:
    - "templates/apache/sites-available/*"
  notify: reload apache

- name: Add additional apache configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-available/{{ item | basename }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob:
    - "templates/apache/conf-available/*"
  notify: reload apache

- name: Activate additional apache configuration
  ansible.builtin.file:
    src: "/etc/apache2/conf-available/{{ item | basename }}"
    dest: "/etc/apache2/conf-enabled/{{ item | basename }}"
    owner: root
    group: root
    state: link
  with_fileglob:
    - "templates/apache/conf-available/*"
  notify: reload apache

- name: Configure apache modules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/apache2/mods-available/{{ item | basename }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_fileglob:
    - "templates/apache/mods-available/*"
  notify: reload apache
