---

- name: Import AMP packaging GPG signing key
  apt_key:
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=wand"
    state: present

- name: Add AMP repository
  apt_repository:
    repo: "deb https://dl.bintray.com/wand/amp {{ansible_distribution_release}} main"
    state: present
