---

- name: Remove AMP bintray repository
  ansible.builtin.apt_repository:
    repo: "deb https://dl.bintray.com/wand/amp {{ ansible_distribution_release }} main"
    state: absent

- name: Remove old packaging GPG signing keys
  ansible.builtin.apt_key:
    id: "{{ bintray_amp_apt_key_fingerprint }}"
    state: "absent"

- name: Remove old AMP apt sources.list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/dl_cloudsmith_io_public_wand_amp_deb_{{ ansible_distribution | lower }}.list
    state: absent

- name: Remove AMP apt signing key from default apt keyring
  ansible.builtin.apt_key:
    id: "{{ amp_apt_key_fingerprint }}"
    keyring: /etc/apt/trusted.gpg
    state: absent

- name: Remove old AMP apt repository entry
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/amp.gpg]
      https://dl.cloudsmith.io/public/wand/amp/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: amp
    update_cache: no
    state: absent

- name: Remove AMP apt signing key from /usr/share/keyrings
  ansible.builtin.file:
    path: /usr/share/keyrings/amp.gpg
    state: absent

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Import AMP packaging GPG signing key
  ansible.builtin.apt_key:
    id: "{{ amp_apt_key_fingerprint }}"
    url: "https://dl.cloudsmith.io/public/wand/amp/gpg.81EB1488CDD7837D.key"
    keyring: /etc/apt/keyrings/amp.gpg
    state: present

- name: Add AMP repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/amp.gpg]
      https://dl.cloudsmith.io/public/wand/amp/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: amp
    state: present
